import { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Header from '@/pages/components/header';
// the style
import styles from '@/styles/gam.module.css';
import { generateEquation } from '@/websocket-server/gen';
import Calc from '@/pages/components/calc';
// font
const inter = Inter({ subsets: ['latin'] })

  export default function Home() {
    const [equation, setEquation] = useState('');
  
    useEffect(() => {
      // Generate an equation when the component mounts
      const newEquation = generateEquation(1); // Replace 1 with the desired level
      setEquation(newEquation.equationString);
    }, []);

  return (
    <>
      <Head>
        <title>Lobby</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.fixed}`}>
        <Header />
        <main className={`${styles.main} ${inter.className}`}>
          <div>
            <h1 className={`${styles.nah}`}>Lobby</h1>
          </div>
          <div className={`${styles.cen}`}>
            <p className={`${styles.p}`}>{equation}</p>
              <div className={`${styles.boxing}`}>
                <div className={`${styles.calc1}`}>{/*calc1*/}
                  <div className={`${styles.res}`}>
                    <input type="number" className={`${styles.in}`} placeholder="0"/>
                  </div>
                    <Calc />
                </div>
              </div>
          </div>
        </main>
      </div>
    </>
  );
}
