import { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Header from '@/pages/components/header';
// the style
import styles from '@/styles/Home.module.css';
// font
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [equation, setEquation] = useState('');

  useEffect(() => {
    const ws = new WebSocket('ws://localhost:8080');

    ws.onopen = () => {
      ws.send(JSON.stringify({ type: 'equation' }));
    };

    ws.onmessage = (message) => {
      const data = JSON.parse(message.data);
      if (data.type === 'equation') {
        setEquation(data.equation);
      }
    };

    return () => {
      ws.close();
    };
  }, []);

  return (
    <>
      <Head>
        <title>Compmath</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.fixed}`}>
        <Header />
        <main className={`${styles.main} ${inter.className}`}>
          <div>
            <h1>Lobby</h1>
          </div>
          <div>
            <p>{equation}</p>
            <div className={`${styles.calc}`}>
              
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
