import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Header from './components/header';
// the style
import styles from '@/styles/Home.module.css';
// font
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Compmath</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.fixed}`}>
        <Header />
        <main className={`${styles.main} ${inter.className}`}>
          <div>
            <h1>CompMath</h1>
          </div>

        </main>
      </div>
    </>
  );
}
